applications:
  app:
    type: composable:25.11
    stack:
      packages:
        - hugo  # Use Hugo from Nix packages for static site generation
        - go    # Required for Hugo modules and theme dependencies
        - curl  # Needed for the DNS API call
        - dig   # Needed to find the IP of the gateway
    hooks:
      build: |
        echo "{\"records\": [\"$(dig +short gw.eu-5.platformsh.site)\"]}" | curl -X PATCH https://desec.io/api/v1/domains/vipau.dev/rrsets/@/A/ --header "Authorization: Token ${DESEC_TOKEN}" --header "Content-Type: application/json" --data @-
        set -ex
        hugo --destination=public
    web:
      commands:
        start: sleep infinity
      locations:
        /:
          root: public
          index:
            - index.html
          expires: 1h
          scripts: false

routes:
  https://{default}/:
    type: upstream
    upstream: app:http
  https://www.{default}/:
    type: upstream
    upstream: app:http
